---
title: "F_PRO_Covid_Jenni_MentaScales_CESD" 
output: html_document
date: "2023-02-08"
---

#Input: 
E_PRO:
--> save(cohortF_Drugs, SSI_SevMod_Base, file = "~/Library/CloudStorage/Box-Box/UCSF_86/Jain_1986/Output_data/cohortF_Drugs_Drugs_SevMod.RData")

MENTAL HEALTH SCALES
##Purpose:
--> General Anxiety Disorder-7 Scale 
Minimal Anxiety (score of 0-4)
Mild Anxiety (score of 5-9)
Moderate Anxiety (score of 10-14)
Severe Anxiety (score >15)

## CES-D
*c/o >=16
https://www.apa.org/pi/about/publications/caregivers/practice-settings/assessment/tools/depression-scale
## PC-PTSD
*>= 33
https://www.ptsd.va.gov/professional/assessment/adult-sr/ptsd-checklist.asp

#Output: 



```{r  global_options, echo=F}
## Setting global options for chunks
knitr::opts_chunk$set(echo = F, message = FALSE,
  warning = FALSE, include = T)
```

```{r loading packages, echo=F, include=F}

pacman::p_load(
  tidyverse,papeR,
  qwraps2,# deduplication, grouping, and slicing functions
  janitor,     # function for reviewing duplicates
  stringr,
  arsenal,data.table,
  tsibble,
  datefixR,
  readr, gt,
  sjmisc,
  labelled,
  crosstable,
  here,         # File locator
  skimr,        # get overview of data
  tidyverse,    # data management + ggplot2 graphics
  gtsummary,    # summary statistics and tests
  rstatix,      # summary statistics and statistical tests
  janitor,      # adding totals and percents to tables
  scales,       # easily convert proportions to percents
  flextable,
  haven, tidyr,
  purrr, artemis, rtemis,
  parsedate, data.table
  ,markdown
,conflicted
,dplyr
,readr
,table1
,readxl
,tidyr
,base
,tableone
,magrittr
,boot
,knitr
,stringr
,compare
,admiral
,lubridate
,tibble
,gtsummary)

conflict_prefer("filter","dplyr")
conflict_prefer("starts_with", "expss")
conflict_prefer("select", "dplyr")#over statslibrary(tidyverse)

# install.packages("remotes")
# remotes::install_github("egenn/rtemis")
# library(rtemis)

#install.packages("remotes")
#remotes::install_github("egenn/rtemis")
```

```{r Cleaning Enviroment}
rm(list= ls()[!(ls() %in% c(''))])

```


#Root functions
```{r Functions, echo=F, include=F}
#Function for sorting the variables by alphabetical order
AlphaColumns <- function(x) {
                      x %>% tibble %>%
                            select("StudyId", sort(colnames(.)))
}

#Looking for something
lkf <- function(d,p) names(d)[grep(p,names(d))]
```


```{r LoadingMental dataset}
PRO_PHQ_DepressionAnxiety <- read.csv("~/Library/CloudStorage/Box-Box/1986 Study/CNICS189_Sept2022/PRO_PHQ_DepressionAnxiety.csv", stringsAsFactors=TRUE)
```

```{r FilteringByDate}
PRO_PHQ_DepressionAnxiety$PRO_Date <- as.Date(PRO_PHQ_DepressionAnxiety$date, tryFormats = "%Y-%m-%d")
range(PRO_PHQ_DepressionAnxiety$PRO_Date)
#"2005-09-22" "2022-05-06"

# Up to 24m before LD
PRO_PHQ_DepressionAnxiety <- PRO_PHQ_DepressionAnxiety %>%
  filter(PRO_Date >= as.Date("2018-03-19"))
range(PRO_PHQ_DepressionAnxiety$PRO_Date)
#"2018-03-19" "2022-05-06"
length(unique(PRO_PHQ_DepressionAnxiety$StudyId))
#10515
```


```{r Estabilishing VisitOrder}
PRO_PHQ_DepressionAnxiety <- PRO_PHQ_DepressionAnxiety %>% 
    group_by(StudyId) %>% 
    dplyr::arrange(StudyId, as.Date(PRO_Date)) %>% 
    mutate(Visit_SurveyOrder = row_number())

range(PRO_PHQ_DepressionAnxiety$Visit_SurveyOrder)
#1 11
```

```{r Checking Variables Mental }
summary(PRO_PHQ_DepressionAnxiety)
```

```{r Selecting variables of interest}
PHQ9 <- PRO_PHQ_DepressionAnxiety %>% 
  select(-c(date))
```

```{r CESD}
# Mental Health  
# Center for Epidemiologic Studies on Depression (CESD)
# Mean Depression Score (SD)
# Symptoms consistent with clinical depression (CESD Score ≥16) (yes/no)


```

```{r PHQ-9 pg16}
PHQ9 <- as.data.frame(PHQ9)

#Qx225 Little interst or pleasure in doing things
tabyl(PHQ9, dep1)
PHQ9 <- PHQ9 %>% mutate(Qx1_PHQ = dplyr::case_when(
   dep1 == "not at all" ~ 1,
   dep1 == "several days" ~ 2 ,
   dep1 ==  "more than half of days" ~ 3,
   dep1 == "nearly every day" ~ 4)
   )

#Qx226 Felling down, depressed, hopeless
tabyl(PHQ9, dep2)
PHQ9 <- PHQ9 %>% mutate(Qx2_PHQ = dplyr::case_when(
   dep2 == "not at all" ~ 1,
   dep2 == "several days" ~ 2 ,
   dep2 ==  "more than half of days" ~ 3,
   dep2 == "nearly every day" ~ 4)
   )

#Qx227 Sleeping
tabyl(PHQ9, dep3)
PHQ9 <- PHQ9 %>% mutate(Qx3_PHQ = dplyr::case_when(
   dep3 == "not at all" ~ 1,
   dep3 == "several days" ~ 2 ,
   dep3 ==  "more than half of days" ~ 3,
   dep3 == "nearly every day" ~ 4)
   )

#Qx228 Tired or little energy
tabyl(PHQ9, dep4)
PHQ9 <- PHQ9 %>% mutate(Qx4_PHQ = dplyr::case_when(
   dep4 == "not at all" ~ 1,
   dep4 == "several days" ~ 2 ,
   dep4 ==  "more than half of days" ~ 3,
   dep4 == "nearly every day" ~ 4)
   )

#Qx229 Appetite
tabyl(PHQ9, dep5)
PHQ9 <- PHQ9 %>% mutate(Qx5_PHQ = dplyr::case_when(
   dep5 == "not at all" ~ 1,
   dep5 == "several days" ~ 2 ,
   dep5 ==  "more than half of days" ~ 3,
   dep5 == "nearly every day" ~ 4)
   )

#Qx230 Bad about yourself
tabyl(PHQ9, dep6)
PHQ9 <- PHQ9 %>% mutate(Qx6_PHQ = dplyr::case_when(
   dep6 == "not at all" ~ 1,
   dep6 == "several days" ~ 2 ,
   dep6 ==  "more than half of days" ~ 3,
   dep6 == "nearly every day" ~ 4)
   )

#Qx231 Concentrating
tabyl(PHQ9, dep7)
PHQ9 <- PHQ9 %>% mutate(Qx7_PHQ = dplyr::case_when(
   dep7 == "not at all" ~ 1,
   dep7 == "several days" ~ 2 ,
   dep7 ==  "more than half of days" ~ 3,
   dep7 == "nearly every day" ~ 4)
   )

#Qx232 Moving or Restless
tabyl(PHQ9, dep8)
PHQ9 <- PHQ9 %>% mutate(Qx8_PHQ = dplyr::case_when(
   dep8 == "not at all" ~ 1,
   dep8 == "several days" ~ 2 ,
   dep8 ==  "more than half of days" ~ 3,
   dep8 == "nearly every day" ~ 4)
   )

#Qx233 Better dead
tabyl(PHQ9, dep9)
PHQ9 <- PHQ9 %>% mutate(Qx9_PHQ = dplyr::case_when(
   dep9 == "not at all" ~ 1,
   dep9 == "several days" ~ 2 ,
   dep9 ==  "more than half of days" ~ 3,
   dep9 == "nearly every day" ~ 4)
   )
```

```{r Summing up the Scores for PHQ-9}
PHQ9 <- PHQ9 %>% rowwise %>%
  mutate(PHQ9_Score = sum(c(Qx1_PHQ,
                                 Qx2_PHQ,
                                 Qx3_PHQ,
                                    Qx4_PHQ,
                                    Qx5_PHQ,
                                    Qx6_PHQ,
                                 Qx7_PHQ,
                                 Qx8_PHQ,
                                 Qx9_PHQ), na.rm=T)
                               )

var_label(PHQ9) <- 
        list(PHQ9_Score = "PHQ9 Score"
         )

range(PHQ9$PHQ9_Score, na.rm=T)

```

```{r ScoreClassification}
#Total scores of 5, 10, 15, and 20 represent cutpoints for mild, moderate, moderately severe and severe depression, respectively.
PHQ9 <- as.data.frame(PHQ9)

tabyl(PHQ9, PHQ9_Score)

PHQ9 <- PHQ9 %>% mutate(DepSeverity = dplyr::case_when(
      PHQ9_Score >=0 & PHQ9_Score <=4 ~ "None-minimal",
      PHQ9_Score >= 5 & PHQ9_Score <= 9 ~ "Mild",
      PHQ9_Score >=10  & PHQ9_Score <= 14 ~ "Moderate",
      PHQ9_Score >= 15 & PHQ9_Score <=19  ~ "Moderately Severe",
      PHQ9_Score >=20 & PHQ9_Score <=27 ~ "Severe"),

    # Convert to factor
    DepSeverity = factor( DepSeverity,
      level = c("None-minimal", "Mild","Moderate","Moderately Severe","Severe")
    )
  )

var_label(PHQ9) <- 
        list(DepSeverity = "Depression Severity"
         )

tabyl(PHQ9, DepSeverity)

```
```{r Subset ONLY the 1st Visit}
PHQ9_Baseline <- subset(PHQ9, Visit_SurveyOrder == 1)

PHQ_preMerge <- PHQ9_Baseline %>% select(StudyId, Site, PHQ9_Score, DepSeverity, Visit_SurveyOrder)
```


```{r Loading Drugs' dataset E_PRO script --> SSIScore / Severity to merge with PHQ9}
load("~/Library/CloudStorage/Box-Box/UCSF_86/Jain_1986/Output_data/cohortF_Drugs_Drugs_SevMod.RData")

```

```{r Cleaning Enviroment}
rm(list= ls()[!(ls() %in% c('PHQ_preMerge', 'lkf', 'AlphaColumns', 'SSI_SevMod_Base'))])
```


```{r Merging to fill the table}
SSI_SevMod_Base$Visit_SurveyOrder <- SSI_SevMod_Base$Visit_SurveyDRUGS_Order

Drugs_Depression <- inner_join(SSI_SevMod_Base,PHQ_preMerge, by=c("StudyId", "Site", "Visit_SurveyOrder"))

```

#TABLE
```{r Editing Tables, echo=F, include=F}
reset_gtsummary_theme()
theme_gtsummary_journal(journal = "lancet")
#> Setting theme `JAMA`
theme_gtsummary_compact()
#> Setting theme `Compact`

```

```{r Baseline Risk, echo=F, include=T}
TabMari <- Drugs_Depression %>%
 select( c("StudyId", "Site", "Age", "Race", "BirthSex", "AnySevMod", "AnySevere","ast_1508_od", "ast_pot2_Bn", "ast_coc2_Bn",
  "ast_pst2_Bn",              "ast_meth2_Bn",             "ast_inh2_Bn",             "ast_sed2_Bn",            
  "ast_hal2_Bn",              "ast_opi2_Bn",              "ast_opip2_Bn",             "ast_her2_Bn",            
  "ast_fen2_Bn",              "ast_narc2_Bn", "AssistRiskScore_CAN", "AssistRiskScore_COCA",   "AssistRiskScore_PxStim" , "AssistRiskScore_HAL", "AssistRiskScore_Her",   
"AssistRiskScore_INH", "AssistRiskScore_METH",   "AssistRiskScore_NARC",   "AssistRiskScore_OpiPx",  "AssistRiskScore_OpiSt", 
 "AssistRiskScore_SED", "AssistRiskScore_FEN","AssistScore_COCA",       "AssistScore_FEN",        "AssistScore_HAL",       
 "AssistScore_HER",        "AssistScore_INH",        "AssistScore_METH",       "AssistScore_NARC",       "AssistScore_OpiPx",     
 "AssistScore_OpiSt",      "AssistScore_POT",        "AssistScore_PxSTIM",     "AssistScore_SED" ,"PolyTwo_Bn","PolyThree_Bn", "PHQ9_Score", "DepSeverity"  )
 )
 TabSevMod <- TabMari %>%
  tbl_summary(by=AnySevMod, missing="no",
              
              
    statistic = list(all_continuous() ~ "{p50} [{p25}-{p75}]; {mean} ({sd})",
                     all_categorical() ~ "{n} / {N} ({p}%)"),
     digits = all_continuous() ~ 0
              
              
              ) %>%
             add_p(pvalue_fun = ~style_pvalue(.x, digits = 2)) %>%
  add_overall() %>%
  add_n() %>% 
  # remove studyId row
  modify_table_body(filter, !(variable == "StudyId"))  %>%
  remove_row_type(BirthSex, type = "level", c("Male", "Intersexed")) %>%
   remove_row_type(Race, type = "level", c("")) %>%
  modify_header(label ~ "**Variable**") %>%
  modify_spanning_header(c("stat_1", "stat_2") ~ "**Any Severe | Moderate SSI Score**") %>%
  modify_footnote(
    all_stat_cols() ~ "Median (IQR) or Frequency (%); Mean (SD); (min-max)"
  ) %>%
  modify_caption("**Table X  Characteristics of a Cohort of People Living with HIV Enrolled in the CFAR Network of Integrated Clinical Systems (CNICS) between 2018 and 2022 (N=XXXX)	by SSI score (Severe) for ANY respective substance at Baseline Visit**") %>%
  bold_labels() %>% 
gtsummary::as_gt() %>%             # convert to gt table
gt::tab_source_note(gt::md("*Jennis's study / CNICS 09feb2023*")) 

 
  TabSevMod %>% gt::gtsave(             # save table as image
    filename = "~/Library/CloudStorage/Box-Box/UCSF_86/LocalRepo/cnics_chvm/FiguresBox/SevereMod_SSI_Depression.html", inline_css = TRUE)

TabSevMod

```